version: "3.7"

services:
  backend:
    image: frappe/erpnext-worker:version-14
    restart: unless-stopped
    environment:
      - SITE_NAME=${SITE_NAME}
      - DB_ROOT_USER=${DB_ROOT_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - INSTALL_APPS=${INSTALL_APPS}
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - db
      - redis-cache
      - redis-queue
      - redis-socketio

  nginx:
    image: frappe/erpnext-nginx:version-14
    restart: unless-stopped
    ports:
      - "${FRAPPE_PORT}:80"
    volumes:
      - sites:/home/frappe/frappe-bench/sites
    depends_on:
      - backend

  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  redis-cache:
    image: redis:6.2
    restart: unless-stopped

  redis-queue:
    image: redis:6.2
    restart: unless-stopped

  redis-socketio:
    image: redis:6.2
    restart: unless-stopped

volumes:
  sites:
  db-data:
